#!/bin/bash
set -euo pipefail
publisher_jar=publisher.jar
input_cache_path=./input-cache/
echo Checking internet connection...
curl -sSf tx.fhir.org > /dev/null

if [ $? -eq 0 ]; then
	echo "Online"
	txoption=""
else
	echo "Offline"
	txoption="-tx n/a"
fi

echo "$txoption"

# Run the script to convert and download the content based on the Excel input.
if [[ ! -d util/scripts/excel-to-artifacts/node_modules ]]; then
	cd util/scripts/excel-to-artifacts
	npm install
	cd ../../..
fi
node util/scripts/excel-to-artifacts/excel-to-artifacts.js input/requirements generated

# Sushi is run automatically by the publisher if the folder input/fsh exists. We're not guaranteed to have this
# folder, but Sushi needs to run to handle sushi-config.yaml -- and besides, we need to do some post-processing.
# So it's called here explicitly, and suppressed from the validator.jar call.
# First remove menu.xml, as it should be generated by Sushi, but Sushi won't generate if it already exists.
if [[ -e input/includes/menu.xml ]]; then
	rm input/includes/menu.xml
fi
sushi .

# Now translate the menu.xml generated by Sushi to English. Please note: menu translation is a hot mess.
# The IG Publisher expects a quite nastily formatted HTML fragment menu.xml file containing the menu, which is not
# really author-friendly. Sushi has fixed this by generating this menu from sushi-config.yaml. However, Sushi doesn't
# support multiple languages. The IG Publisher does, if you give it the HTML fragment with the translations.
# We 'solve' this using a custom script that translates the menu.xml generated by Sushi using a regular .po file.
# However, this is only picked up if both the original menu.xml and the translated menu.xml files are placed in the
# input folder, where normally the checked-in, non-generated content resides. So the files are copied there just before
# calling the IG Publisher and are excluded from git.
if [[ ! -d util/scripts/translate-menu/node_modules ]]; then
	cd util/scripts/translate-menu
	npm install
	cd ../../..
fi
node util/scripts/translate-menu/translate-menu.js --lang en

export JAVA_TOOL_OPTIONS="-Dfile.encoding=UTF-8"

publisher=$input_cache_path/$publisher_jar
if test -f "$publisher"; then
	java -jar $publisher -ig . -no-sushi $txoption $*
else
	publisher=../$publisher_jar
	if test -f "$publisher"; then
		java -jar $publisher -ig . -no-sushi $txoption $*
	else
		echo IG Publisher NOT FOUND in input-cache or parent folder.  Please run _updatePublisher.  Aborting...
	fi
fi