@ECHO OFF
SET publisher_jar=publisher.jar
SET input_cache_path=%CD%\input-cache

ECHO Checking internet connection...
powershell -Command "try { $r=[System.Net.WebRequest]::Create('https://tx.fhir.org/r4/metadata'); $r.Timeout=4000; $r.GetResponse().Close(); exit 0 } catch { exit 1 }"
IF %ERRORLEVEL% EQU 0 GOTO isonline
ECHO We're offline...
SET txoption=-tx n/a
GOTO igpublish

:isonline
ECHO We're online
SET txoption=

REM Run the script to convert and download the content based on the Excel input.
IF NOT EXIST util\scripts\excel-to-artifacts\node_modules (
	CD util\scripts\excel-to-artifacts
	CALL npm install
	CD ..\..\..
)
node util\scripts\excel-to-artifacts\excel-to-artifacts.js input\requirements generated
if errorlevel 1 exit /b %errorlevel%

:igpublish

REM Sushi is run automatically by the publisher if the folder input/fsh exists. We're not guaranteed to have this
REM folder, but Sushi needs to run to handle sushi-config.yaml -- and besides, we need to do some post-processing.
REM So it's called here explicitly, and suppressed from the validator.jar call.
REM First remove menu.xml, as it should be generated by Sushi, but Sushi won't generate if it already exists.
IF EXIST input\includes\menu.xml (
	DEL input\includes\menu.xml
)
CALL sushi build .

REM Now translate the menu.xml generated by Sushi to English. Please note: menu translation is a hot mess.
REM The IG Publisher expects a quite nastily formatted HTML fragment menu.xml file containing the menu, which is not
REM really author-friendly. Sushi has fixed this by generating this menu from sushi-config.yaml. However, Sushi doesn't
REM support multiple languages. The IG Publisher does, if you give it the HTML fragment with the translations.
REM We 'solve' this using a custom script that translates the menu.xml generated by Sushi using a regular .po file.
REM However, this is only picked up if both the original menu.xml and the translated menu.xml files are placed in the
REM input folder, where normally the checked-in, non-generated content resides. So the files are copied there just before
REM calling the IG Publisher and are excluded from git.
IF NOT EXIST util\scripts\translate-menu\node_modules (
	CD util\scripts\translate-menu
	CALL npm install
	CD ..\..\..
)
node util\scripts\translate-menu\translate-menu.js --lang en

SET JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8

IF EXIST "%input_cache_path%\%publisher_jar%" (
	JAVA -jar "%input_cache_path%\%publisher_jar%" -ig . -no-sushi %txoption% %*
) ELSE If exist "..\%publisher_jar%" (
	JAVA -jar "..\%publisher_jar%" -ig . -no-sushi %txoption% %*
) ELSE (
	ECHO IG Publisher NOT FOUND in input-cache or parent folder.  Please run _updatePublisher.  Aborting...
)

PAUSE