id: nictiz.nl.nlps
canonical: http://ig.nictiz.nl/nlps
name: PatientSummary
title: PatientSummary IG NL
description: This FHIR IG contains the Dutch Patient Summary built from EHDS compliant generic building blocks. This Patient Summary has Dutch additional specifications but is EHDS first.
status: draft
version: 1.0.0-alpha.1
fhirVersion: 4.0.1
copyrightYear: 2026+
releaseLabel: Alpha

publisher:
  name: Nictiz
  url: https://nictiz.nl

parameters:
  excludettl: true

  path-resource:
    - generated/requirements
    - generated/logicalmodels
    - generated/vocabulary
    - generated/resources

  path-pages:
    - generated/pagecontent

  i18n-default-lang: nl
  i18n-lang: en

  translation-sources:
    - input/translations/en
    - input/translations/nl

  logging: progress
  path-liquid-template: template/liquid

menu:
  Home: index.html
  Background: background.html
  Functional Design: functional-design.html
  Technical Design: technical-design.html

  Requirements:
    Overview: PatientSummary.html
    Requirements: Requirements-PatientSummary.html

  Specification:
    Logical Model: StructureDefinition-LogicalModelPatientSummary.html
    FHIR Profile: StructureDefinition-nl-PatientSummary.html
    Dependencies: dependencies.html   

  Testing: testing.html
  Validation: validation.html
  Artefacts: artifacts.html

instanceOptions:
  manualSliceOrdering: true
  
dependencies:
  hl7.fhir.uv.xver-r5.r4: 0.1.0
  nictiz.nl.gbb: 1.0.0-alpha.1
  hl7.fhir.eu.eps: 1.0.0-ballot