id: nictiz.nl.nlps
canonical: http://ig.nictiz.nl/nlps
name: PatientSummary
status: draft
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2026+
releaseLabel: Alpha

publisher:
  name: Nictiz
  url: https://nictiz.nl

parameters:
  excludettl: true

  path-resource:
    - generated/requirements
    - generated/logicalmodels
    - generated/vocabulary
    - generated/resources

  path-pages:
    - generated/pagecontent

  i18n-default-lang: nl
  i18n-lang: en

  translation-sources:
    - input/translations/en
    - input/translations/nl

  logging: progress
  path-liquid-template: template/liquid

menu:
  Home: index.html
  Functioneel ontwerp: functional-design.html
  Technisch ontwerp: technical-design.html

  Requirements:
    Overzicht: PatientSummary.html
    Requirements: Requirements-PatientSummary.html

  Specificatie:
    Logisch model: StructureDefinition-LogicalModelPatientSummary.html
    FHIR-profiel: StructureDefinition-nl-PatientSummary.html
    Afhankelijkheden: dependencies.html   

  Artefacten: artifacts.html

instanceOptions:
  manualSliceOrdering: true
  
dependencies:
  hl7.fhir.uv.xver-r5.r4: 0.1.0
  nictiz.nl.gbb: 1.0.0-alpha.1
  hl7.fhir.eu.eps: 1.0.0-ballot